# Generated by Django 3.1.7 on 2021-04-05 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keys',
            old_name='keys',
            new_name='key',
        ),
    ]
